version: '2'
services:
    db2:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: recognition
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    api:
        image: recognize/recognition 
        ports:
            - "8080:8080"
        links:
            - db2    